# Generated by Django 3.2.9 on 2021-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
