# Generated by Django 3.2.9 on 2021-12-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('singer_name', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
            ],
            options={
                'verbose_name': 'consert',
                'verbose_name_plural': 'conserts',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='TimeConsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('start', 'start'), ('end', 'end'), ('cancel', 'cancel'), ('sales', 'sales')], max_length=50)),
                ('consert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketSales.consert', verbose_name='time consert')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketSales.location', verbose_name='time location')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
    ]
