# Generated by Django 3.2.9 on 2021-12-07 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketSales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consert',
            name='poster',
            field=models.ImageField(null=True, upload_to='consertPoster/'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='ticketImages/')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketSales.timeconsert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
