# Generated by Django 3.2.9 on 2021-12-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0002_auto_20211207_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeconsert',
            name='status',
        ),
    ]
